# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'UiPath Orchestrator'
    processName: 'RPAChallenge'
    folderName: 'Proto'
    user: 'Antonio Castro'
    machine: 'Antonio''s Machine'
  displayName: 'Orchestrator Run Job'
